### ISSUE TITLE
Allow resource namespace to be set per-manifest

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-k8s_manifests#2]
I've been using this role in a playbook where the playbook is basically run once per namespace... but now that I'm wanting to use it in a playbook where I have a bunch of manifests in different namespaces, I'm finding the global `k8s_resource_namespace` to be a bit limiting.

I would maybe rather have the role have something like:

```yaml
k8s_manifests:
  - dir: ingress/traefik
    namespace: traefik
```

If a namespace is not set, the loop for the manifests will do nothing with namespaces (and the global task for it will be used).

If a namespace is set, the loop will ensure the namespace exists.

**Comment by geerlingguy** [comment]
Urgh... now I'm hitting:

  - https://github.com/ansible/ansible/issues/26336
  - https://github.com/ansible/ansible/issues/35398

I'm trying to add `delegate_to` to the `import_role` to make sure the manifests role is _only_ run on localhost, since that's its typical usage pattern:

```yaml
    - include_role:
        name: geerlingguy.k8s_manifests
      tags: ['kubernetes', 'nfs', 'drupal', 'registry']
      delegate_to: localhost
      become: false
      run_once: true
```

But it looks like that is not allowed. You have to use `import_role` for `delegate_to` (and other attributes) to be applied properly to the entire included (ahem... _imported_) role.

So this looks like it may work:

```yaml
    - import_role:
        name: geerlingguy.k8s_manifests
      tags: ['kubernetes', 'nfs', 'drupal', 'registry']
      delegate_to: localhost
      become: false
      run_once: true
```
