### ISSUE TITLE
After adding role, I got 'python not found' when gathering facts

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-k8s_manifests#3]
Full error message:

```
TASK [Gathering Facts] *********************************************************
fatal: [kube1]: FAILED! => changed=false 
  module_stderr: |-
    Warning: Permanently added '192.168.77.2' (ECDSA) to the list of known hosts.
    /bin/sh: 1: /usr/local/opt/python@2/bin/python2.7: not found
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 127
```

I was wondering why all the sudden a playbook to which I added this role started throwing the above error... and as it turns out, the default of:

```yaml
ansible_python_interpreter: '{{ ansible_playbook_python }}'
```

Seems to make it so that even if I'm delegating _this_ role to localhost, the `ansible_python_interpreter` is overwritten for _all_ hosts. So I had to explicitly define it in `--extra-vars` to counteract this role.

Not 100% sure why I have that defined in `defaults` though :/

**Comment by geerlingguy** [comment]
So I could get it to work by setting in my playbook vars:

```yaml
ansible_python_interpreter: python
```

Then adding a task before importing/including this role:

```yaml
    - name: Set the python interpreter appropriately.
      set_fact:
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
```
